version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "1935:1935"
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
